---
title: "Visualize Pixy results"
format:
  html:
    code-fold: show
    code-tools: true
toc: true
toc-title: Document Contents
number-sections: true
embed-resources: true
---


### Read in data and create long-format table to hold it
```{r}
#open a dataframe to hold all data together
complete.df<-c()

#in a loop, read in each dataframe, rename according to that sample, and combine
for (i in 1:length(pixy_files)){
  #read in dataframe
  df<-read.table(pixy_files[i], header = T)
  df$pop<-gsub("_pi.txt","",gsub("/Users/devonderaad/Desktop/2026.eagle.mountain/pixy/","",pixy_files[i]))
  complete.df<-rbind.data.frame(complete.df,df)
}

#check this worked
table(complete.df$pop)
```

### Plot genetic diversity along chrom1
```{r}
for (i in 1:length(unique(complete.df$pop))){
  print(
# plotting summary statistics along a single chromosome
complete.df %>%
  filter(chromosome == "NC_091017.1") %>%
  filter(pop == unique(complete.df$pop)[i]) %>%
  mutate(chr_position = ((window_pos_1 + window_pos_2)/2)/1000000) %>%
  ggplot(aes(x = chr_position, y = avg_pi*1000))+
  geom_col(fill="black")+
  xlab(paste("Position on Chromosome 1 (Mb) -",unique(complete.df$pop)[i]))+
  ylab("Hets per Kb")+
  theme_bw()+
  scale_x_continuous(expand = c(0, 0))+
  scale_y_continuous(expand = c(0, 0))
)
}

```

### investigate
```{r}
#Aph_californica_93535 seems to have a big ROH chunk in the middle of chrom1
#investigate further
test<-complete.df[complete.df$pop=="Aph_californica_93535",]
#looks like 76-86Mb is a ~10Mb ROH in this individual
#did it get successfully called using BCFtools ROH?
rohtable <- read.table("~/Desktop/2026.eagle.mountain/roh.output/Aph_californica_93535.processed.roh.txt", header=FALSE)
colnames(rohtable)<-c("RG","Sample","Chromosome","Start","End","Length","Number.of.markers","Quality")

```

### Calc genetic diversity per sample
```{r}
#open a new dataframe to store this information
gendiv.df<-data.frame(samp=character(),
                      gendiv=numeric())

#using a for loop, calculate genome-wide genetic diversity in each sample and store it in a dataframe
for (i in 1:length(unique(complete.df$pop))){
  
  ### isolate the given sample
  x <- complete.df[complete.df$pop == unique(complete.df$pop)[i],]
  
  #exclude the Z, W, and mtDNA scaffolds:
  x<-x[x$chromosome != "NC_138418.1" & x$chromosome != "NC_138417.1" & x$chromosome != "NC_051467.1",]
  
  #calculate the proportion of het sites across all called sites for this genome
  #store in df alongside sample info
  gendiv.df[i,]<-c(unique(complete.df$pop)[i],sum(x$count_diffs, na.rm = TRUE) / sum(x$no_sites, na.rm = TRUE))
}

```


### plot gen div per sample
```{r}
#load libraries
library(ggplot2)
library(gghalves)

#make numeric
gendiv.df$gendiv<-as.numeric(gendiv.df$gendiv)

#add subspecies info to data frame
gendiv.df$subspecies<-c(rep("cali", times=3),rep("obsc", times=6),"hypo",rep("obsc", times=3),rep("cana", times=3),"gris","gris",rep("nev", times=3),"gris","wood")

#add sample type info
gendiv.df$type<-c(rep("muscle", times=10),rep("toepad", times=8),rep("muscle", times=3),rep("toepad", times=2))

#reorder factors for plotting
gendiv.df$subspecies <- factor(gendiv.df$subspecies, levels = unique(gendiv.df$subspecies))

#plot
ggplot(gendiv.df, aes(x = subspecies, y = gendiv*1000, shape=type)) +
  geom_half_boxplot(side = "l", outlier.shape = NA, errorbar.draw = FALSE) +
  geom_half_point(side = "r", transformation = position_jitter(width = 0.05, height = 0)) +
  labs(y = "Heterozygous sites per Kb") +
  theme_classic()

#replot
ggplot(gendiv.df, aes(x = subspecies, y = gendiv*1000)) +
  geom_half_boxplot(side = "l", outlier.shape = NA, errorbar.draw = FALSE) +
  geom_half_point(side = "r", transformation = position_jitter(width = 0.05, height = 0)) +
  labs(y = "Heterozygous sites per Kb") +
  theme_classic()

#save
plotx<-ggplot(gendiv.df, aes(x = subspecies, y = gendiv*1000)) +
  geom_half_boxplot(side = "l", outlier.shape = NA, errorbar.draw = FALSE) +
  geom_half_point(side = "r", transformation = position_jitter(width = 0.05, height = 0)) +
  labs(y = "Heterozygous sites per Kb") +
  theme_classic()

#ggsave("~/Desktop/2026.eagle.mountain/gendiv.pdf", plotx, width = 6.5, height = 2, units = "in")

```

