---
title: "run ADMIXTURE on UCLA cluster"
format:
  html:
    code-fold: show
    code-tools: true
toc: true
toc-title: Document Contents
number-sections: true
embed-resources: true
---

### Set up input files
```{r}
library(vcfR)
library(SNPfiltR)
library(ggplot2)
#read in thinned vcf
v<-read.vcfR("~/Desktop/2026.eagle.mountain/final.trimmed.snps.5KBthinned.vcf.gz")
#get details on this SNP dataset
v

#ADMIXTURE will be run on this filtered, thinned vcf. To also ensure that related individuals are not biasing our results, I will trim out one related individual from the putative sibling pair of Aphelocoma californica cana, that we previously identified using Plink to make a KING relatedness matrix

#remove one of the two related samples
vtrim<-v[,colnames(v@gt) != "Aph_californica_94204"]
#remove invariant sites
vtrim<-min_mac(vtrim, min.mac = 1)
#check out info on this dataset
vtrim
#write to disk
#vcfR::write.vcf(vtrim, file="~/Desktop/2026.eagle.mountain/unrelated.trimmed.vcf.gz")
```

### run *ADMIXTURE* on the UCLA cluster
```{bash, eval=FALSE}
#use these bash commands to unzip the vcf files you just wrote out before going on to the next step
gunzip final.trimmed.snps.5KBthinned.vcf.gz

#use this thinned vcf file to execute ADMIXTURE on the cluster using this script submitted as a slurm job:

#### submit_job.sh START ####
#!/bin/bash
#$ -cwd
#$ -o ./joblog.$JOB_ID.txt                   #set the job log output file
#$ -j y                                      #set error = Merged with joblog
#$ -l h_rt=1:00:00,h_data=3G      #specify requested resources (h_rt gives time request in 'hrs:mins:secs' format) (h_data specifies requested RAM per task) (highp=TRUE means run it on Aguillon Lab owned nodes)
#$ -pe shared 10                              #specify number of CPUs requested

#load necessary modules
. /u/local/Modules/default/init/modules.sh
#load plink #(v1.90b6.24)
module load plink/1.90b624

#use plink to convert vcf directly to bed format:
plink --vcf final.trimmed.snps.5KBthinned.vcf --double-id --allow-extra-chr --make-bed --out binary_fileset
#fix chromosome names
cut -f2- binary_fileset.bim  > temp
awk 'BEGIN{FS=OFS="\t"}{print value 1 OFS $0}' temp > binary_fileset.bim

#run admixture for a K of 1-10, using cross-validation, with 10 threads
for K in 1 2 3 4 5 6 7 8 9 10; 
do /u/project/aguillon/shared_bin/admixture_linux-1.3.0/admixture --cv -j10 binary_fileset.bed $K | tee log${K}.out;
done

#Which K iteration is optimal according to ADMIXTURE ?
grep -h CV log*.out > log.errors.txt
```

### Assess the best run based on cross-validation
```{r}
#Now copy your entire admixture directory into your local machine, in bash, using a command like this:
#scp -r 'dderaad@dtn.hoffman2.idre.ucla.edu:/u/home/d/dderaad/project-aguillon/eagle.mountain.scrubjays/main.text/admixture' /Users/devonderaad/Desktop/2026.eagle.mountain/

#read in ADMIXTURE results to R
#setwd to the admixture directory you brought in from the cluster
setwd("~/Desktop/2026.eagle.mountain/admixture")

#read in log error values to determine optimal K
log<-read.table("log.errors.txt")[,c(3:4)]
#use double backslash to interpret the opening parentheses literally in the regular expression
log$V3<-gsub("\\(K=", "", log$V3)
log$V3<-gsub("):", "", log$V3)
#interpret K values as numerical
log$V3<-as.numeric(log$V3)
#rename columns
colnames(log)<-c("Kvalue","cross.validation.error")

#make plot showing the cross validation error across K values 1:10
ggplot(data=log, aes(x=Kvalue, y=cross.validation.error, group=1)) +
  geom_line(linetype = "dashed")+
  geom_point()+
  ylab("cross-validation error")+
  xlab("K")+
  scale_x_continuous(breaks = c(1:10))+
  theme_classic()
#lowest CV value is the ideal K value
```


### Visualize results as bar charts
```{r}
#setwd to the admixture directory you brought in from the cluster
setwd("~/Desktop/2026.eagle.mountain/admixture")

#read in input file
sampling<-read.table("binary_fileset.fam")[,1]
#get list of input samples in order they appear
sampling

#read in all ten runs and save each dataframe in a list
runs<-list()
#read in log files
for (i in 1:10){
  runs[[i]]<-read.table(paste0("binary_fileset.", i, ".Q"))
}

#plot runs 1:5
par(mfrow=c(1,1))
for (i in 1:5){
barplot(t(as.matrix(runs[[i]])), col=rainbow(i), ylab="Ancestry", border="black")
}

#isolate run 2 (best according to CV)
run2<-runs[[2]]
#add sample info in the correct order (same as input vcf)
run2$sample<-colnames(v@gt)[-1]

#reorder so that the order matches subspecies designations
run2.reord<-run2[c(4:9,11:13,1:3,10,15,16,14,19:21,17,18,22,23),]

#plot barplots organized based on sampling details
barplot(t(as.matrix(run2.reord[,c(1,2)])), col=c("#ed2726","#3367b1"), ylab="Ancestry", border="black", names.arg=c(run2.reord$sample), cex.names=0.35, las=2,
        space=c(0,rep(0, times=8),0.5,rep(0, times=2),0.5,0.5,
                rep(0, times=2),0.5,rep(0, times=2),0.5,
                rep(0, times=2),0.5))

#save barplot output to use in the construction of multipanel Fig. 1 in Adobe Illustrator
## 1. Open a pdf file
#pdf("~/Desktop/2026.eagle.mountain/admixture/admixture.pdf", width=7.25, height=2.9) 
## 2. Create a plot
barplot(t(as.matrix(run2.reord[,c(1,2)])), col=c("#ed2726","#3367b1"), ylab="Ancestry", border="black", names.arg=c(run2.reord$sample), cex.names=0.35, las=2,
        space=c(0,rep(0, times=8),0.5,rep(0, times=2),0.5,0.5,
                rep(0, times=2),0.5,rep(0, times=2),0.5,
                rep(0, times=2),0.5))
## 3. Close the plot
#dev.off()
```

### repeat this whole procedure using the dataset with related individuals removed
```{bash, eval=FALSE}
#use these bash commands to unzip the vcf files you just wrote out before going on to the next step
gunzip unrelated.trimmed.vcf.gz

#use this thinned vcf file to execute ADMIXTURE on the cluster using this script submitted as a slurm job:

#### submit_job.sh START ####
#!/bin/bash
#$ -cwd
#$ -o ./joblog.$JOB_ID.txt                   #set the job log output file
#$ -j y                                      #set error = Merged with joblog
#$ -l h_rt=1:00:00,h_data=3G      #specify requested resources (h_rt gives time request in 'hrs:mins:secs' format) (h_data specifies requested RAM per task) (highp=TRUE means run it on Aguillon Lab owned nodes)
#$ -pe shared 10                              #specify number of CPUs requested

#load necessary modules
. /u/local/Modules/default/init/modules.sh
#load plink #(v1.90b6.24)
module load plink/1.90b624

#use plink to convert vcf directly to bed format:
plink --vcf unrelated.trimmed.vcf --double-id --allow-extra-chr --make-bed --out binary_fileset
#fix chromosome names
cut -f2- binary_fileset.bim  > temp
awk 'BEGIN{FS=OFS="\t"}{print value 1 OFS $0}' temp > binary_fileset.bim

#run admixture for a K of 1-10, using cross-validation, with 10 threads
for K in 1 2 3 4 5 6 7 8 9 10; 
do /u/project/aguillon/shared_bin/admixture_linux-1.3.0/admixture --cv -j10 binary_fileset.bed $K | tee log${K}.out;
done

#Which K iteration is optimal according to ADMIXTURE ?
grep -h CV log*.out > log.errors.txt
```

### Assess the best run based on cross-validation
```{r}
#Now copy your entire admixture directory into your local machine, in bash, using a command like this:
#scp -r 'dderaad@dtn.hoffman2.idre.ucla.edu:/u/home/d/dderaad/project-aguillon/eagle.mountain.scrubjays/main.text/admixture/remove.unrelated' /Users/devonderaad/Desktop/2026.eagle.mountain/admixture

#read in ADMIXTURE results to R
#setwd to the admixture directory you brought in from the cluster
setwd("~/Desktop/2026.eagle.mountain/admixture/remove.unrelated/")

#read in log error values to determine optimal K
log<-read.table("log.errors.txt")[,c(3:4)]
#use double backslash to interpret the opening parentheses literally in the regular expression
log$V3<-gsub("\\(K=", "", log$V3)
log$V3<-gsub("):", "", log$V3)
#interpret K values as numerical
log$V3<-as.numeric(log$V3)
#rename columns
colnames(log)<-c("Kvalue","cross.validation.error")

#make plot showing the cross validation error across K values 1:10
ggplot(data=log, aes(x=Kvalue, y=cross.validation.error, group=1)) +
  geom_line(linetype = "dashed")+
  geom_point()+
  ylab("cross-validation error")+
  xlab("K")+
  scale_x_continuous(breaks = c(1:10))+
  theme_classic()
#lowest CV value is the ideal K value
```

### Visualize results as bar charts
```{r}
#setwd to the admixture directory you brought in from the cluster
setwd("~/Desktop/2026.eagle.mountain/admixture/remove.unrelated/")

#read in input file
sampling<-read.table("binary_fileset.fam")[,1]
#get list of input samples in order they appear
sampling

#read in all ten runs and save each dataframe in a list
runs<-list()
#read in log files
for (i in 1:10){
  runs[[i]]<-read.table(paste0("binary_fileset.", i, ".Q"))
}

#plot runs 1:5
par(mfrow=c(1,1))
for (i in 1:5){
barplot(t(as.matrix(runs[[i]])), col=rainbow(i), ylab="Ancestry", border="black")
}

#isolate run 2 (best according to CV)
run2<-runs[[2]]
#add sample info in the correct order (same as input vcf)
run2$sample<-colnames(vtrim@gt)[-1]

#reorder so that the order matches subspecies designations
run2.reord<-run2[c(4:9,11:13,1:3,10,15,14,18:20,16,17,21,22),]

#plot barplots organized based on sampling details
barplot(t(as.matrix(run2.reord[,c(1,2)])), col=c("#ed2726","#3367b1"), ylab="Ancestry", border="black", names.arg=c(run2.reord$sample), cex.names=0.35, las=2,
        space=c(0,rep(0, times=8),0.5,rep(0, times=2),0.5,0.5,
                rep(0, times=1),0.5,rep(0, times=2),0.5,
                rep(0, times=2),0.5))

#save barplot output to use in the construction of multipanel Fig. 1 in Adobe Illustrator
## 1. Open a pdf file
#pdf("~/Desktop/2026.eagle.mountain/admixture/admixture.trimmed.pdf", width=7.25, height=2.9) 
## 2. Create a plot
barplot(t(as.matrix(run2.reord[,c(1,2)])), col=c("#ed2726","#3367b1"), ylab="Ancestry", border="black", names.arg=c(run2.reord$sample), cex.names=0.35, las=2,
        space=c(0,rep(0, times=8),0.5,rep(0, times=2),0.5,0.5,
                rep(0, times=1),0.5,rep(0, times=2),0.5,
                rep(0, times=2),0.5))
## 3. Close the plot
#dev.off()
```

